# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07cc8b883c1a7393697540a36a81209346c3889597671f37e31c8bf9f912a38d70e3d38eb6c2c2a56a9c4fc32f5783c405d059ec4f5c2c1785cc2ca6e081091b

test:
  secret_key_base: a7d86016a0a39fae0ca77840d6ae1deec6867c963ce3dcce2217fc5b679e91ad42275fc8bb1fb3e074f3db9440dbd4919d5a8e352f9a37bc5a27ea541612da53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
